# Source: nack
apiVersion: jetstream.nats.io/v1beta2
kind: Account
metadata:
  name: app
  namespace: nats
  annotations:
    noa.re/manifest-id: 73936849d52f293c
spec:
  token:
    file: /var/run/secrets/tokens/nats
