# Source: nack
apiVersion: jetstream.nats.io/v1beta2
kind: Consumer
metadata:
  name: argo-poker
  namespace: nats
  annotations:
    noa.re/manifest-id: d92e74067e6d7245
spec:
  streamName: github-events
  durableName: argo-poker
  filterSubjects:
  - idcat.github.events.push.nresare.fruktsallad
  ackPolicy: explicit
  deliverPolicy: last
  account: app
