# Source: nats-aws-auth
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-aws-auth
  labels:
    app: nats-aws-auth
  namespace: nats
  annotations:
    noa.re/manifest-id: 72cd27eb114dd1db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-aws-auth
  template:
    metadata:
      labels:
        app: nats-aws-auth
      annotations:
        checksum/config: 0eaeaee89edce81f92ccf316fda927c78723e99ffa4bc9b11c283f4c82425927
    spec:
      containers:
      - name: nats-aws-auth
        image: nresare/nats-aws-auth:v2026.02.19-1de79ca-12-gafc222e
        ports:
        - name: http
          containerPort: 8080
        args:
        - --url=nats://nats.nats
        - --auth-backend=k8s-oidc
        - --jwt-issuer=https://k8s.noa.re
        - --config=/config/nats-aws-auth.toml
        - --key-storage=directory
        - --key-dir=/keys
        volumeMounts:
        - name: nats-aws-auth-config
          mountPath: /config
        - name: keys
          mountPath: /keys
      volumes:
      - name: nats-aws-auth-config
        configMap:
          name: nats-aws-auth-config
      - name: keys
        secret:
          secretName: keys
