# Source: nack
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jetstream-controller
  namespace: nats
  labels:
    app: nack
    chart: nack-0.35.0
  annotations:
    noa.re/manifest-id: 5c532d47568f9e8f
