# Source: loki
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-runtime
  namespace: loki
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
    app.kubernetes.io/version: 3.7.8
  annotations:
    noa.re/manifest-id: 51d3b941b62d8789
data:
  runtime-config.yaml: |
    {}
