# Source: loki
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki-gateway
  namespace: loki
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
    app.kubernetes.io/version: 3.7.7
    app.kubernetes.io/component: gateway
  annotations:
    noa.re/manifest-id: 2d9b9ab1704c8cba
automountServiceAccountToken: false
