# Source: loki
apiVersion: v1
kind: Service
metadata:
  name: loki-headless
  namespace: loki
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
    app.kubernetes.io/version: 3.7.7
    app.kubernetes.io/component: single-binary
    prometheus.io/service-monitor: 'false'
    variant: headless
  annotations:
    noa.re/manifest-id: 1e8ad69aa360cbfc
spec:
  clusterIP: None
  type: ClusterIP
  publishNotReadyAddresses: true
  ports:
  - name: http-metrics
    port: 3100
    targetPort: http-metrics
    protocol: TCP
  - name: grpc
    port: 9095
    targetPort: grpc
    protocol: TCP
  - name: grpclb
    port: 9096
    targetPort: grpc
    protocol: TCP
  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
    app.kubernetes.io/component: single-binary
