# Source: loki
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki-memcached
  namespace: loki
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
    app.kubernetes.io/version: 3.7.8
    app.kubernetes.io/component: memcached
  annotations:
    noa.re/manifest-id: a0623d882fe6b02b
automountServiceAccountToken: false
