# Source: loki
apiVersion: v1
kind: Service
metadata:
  name: loki-gateway-exporter
  namespace: loki
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
    app.kubernetes.io/version: 3.7.8
    app.kubernetes.io/component: gateway
  annotations:
    noa.re/manifest-id: 98c2f3e471e9c0b7
spec:
  type: ClusterIP
  ports:
  - name: http-metrics
    port: 4040
    targetPort: http-metrics
    protocol: TCP
  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
    app.kubernetes.io/component: gateway
