# Source: loki
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: loki
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
    app.kubernetes.io/version: 3.7.8
    app.kubernetes.io/component: single-binary
  annotations:
    noa.re/manifest-id: 877b24cddf9f44e6
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  ports:
  - name: http-metrics
    port: 3100
    targetPort: http-metrics
    protocol: TCP
  - name: grpc
    port: 9095
    targetPort: grpc
    protocol: TCP
  - name: grpclb
    port: 9096
    targetPort: grpc
    protocol: TCP
  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
    app.kubernetes.io/component: single-binary
