# Source: loki
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki-canary
  namespace: loki
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
    app.kubernetes.io/version: 3.7.7
    app.kubernetes.io/component: canary
  annotations:
    noa.re/manifest-id: c24f8a89c42246f4
automountServiceAccountToken: false
