# Source: loki
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki-canary
  namespace: loki
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
    app.kubernetes.io/version: 3.7.8
    app.kubernetes.io/component: canary
  annotations:
    noa.re/manifest-id: 1896312a9a34da48
automountServiceAccountToken: false
