# Source: loki
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki-gateway
  namespace: loki
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
    app.kubernetes.io/version: 3.7.8
    app.kubernetes.io/component: gateway
  annotations:
    noa.re/manifest-id: 160ec93c38208798
automountServiceAccountToken: false
