# Source: repo.noa.re
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: repo-noa-re
  namespace: reposnake
  annotations:
    noa.re/manifest-id: 5f75a2ed5d99b943
spec:
  dnsNames:
  - repo.noa.re
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Always
  secretName: repo-noa-re-tls
