# Source: repo.noa.re
apiVersion: v1
kind: Service
metadata:
  name: repo-noa-re
  namespace: reposnake
  annotations:
    noa.re/manifest-id: 143a35ef22d04b09
spec:
  selector:
    app: repo-noa-re
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
