# Source: demo.resare.com
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-resare-com
  labels:
    app: demo-resare-com
  namespace: oidc-client-demo
  annotations:
    noa.re/manifest-id: 9c1e1947b8bfb181
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-resare-com
  template:
    metadata:
      labels:
        app: demo-resare-com
      annotations:
        checksum/config: 619714723c90c34f0957f6d2ba45525b5935d1915d438f27b625604b8638d49e
    spec:
      containers:
      - name: demo-resare-com
        image: repo.noa.re/oidc-client-demo:0.1.0-7c1fd01a
        args:
        - -c
        - /config/config.toml
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
        volumeMounts:
        - name: demo-resare-com-config
          mountPath: /config
        - name: secret
          mountPath: /secret
        - name: random-secrets
          mountPath: /random-secrets
      volumes:
      - name: demo-resare-com-config
        configMap:
          name: demo-resare-com-config
      - name: secret
        secret:
          secretName: secret
      - name: random-secrets
        secret:
          secretName: demo-resare-com
