# Source: demo.resare.com
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: demo-resare-com
  namespace: oidc-client-demo
  annotations:
    noa.re/deploy-id: dc003dfbf789b829
spec:
  gatewayClassName: eg
  listeners:
  - name: demo-resare-com
    protocol: HTTPS
    hostname: demo.resare.com
    port: 443
    tls:
      certificateRefs:
      - name: demo-resare-com-tls
        group: ''
        kind: Secret
