# Source: demo.resare.com
apiVersion: noa.re/v1alpha1
kind: RandomSecret
metadata:
  name: demo-resare-com
  namespace: oidc-client-demo
  annotations:
    noa.re/manifest-id: 9f8f3c0c9e6e16d4
spec:
  secrets:
  - name: session-key
