# Source: demo.resare.com
apiVersion: noa.re/v1alpha1
kind: RandomSecret
metadata:
  name: demo-resare-com
  namespace: oidc-client-demo
  annotations:
    noa.re/deploy-id: dc003dfbf789b829
spec:
  secrets:
  - name: session-key
