# Source: demo.resare.com
apiVersion: v1
kind: Service
metadata:
  name: demo-resare-com
  namespace: oidc-client-demo
  annotations:
    noa.re/manifest-id: 83d1775bca5e1873
spec:
  selector:
    app: demo-resare-com
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
