# Source: alloy
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: alloy
  namespace: alloy
  labels:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/instance: alloy
    app.kubernetes.io/version: v1.19.2
    app.kubernetes.io/part-of: alloy
    app.kubernetes.io/component: rbac
  annotations:
    noa.re/manifest-id: 9d158ebebc0d8929
