# Source: csi-drivers
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: fruktsallad
  namespace: rook-ceph
  annotations:
    noa.re/manifest-id: bf5ebfa8c80b0d12
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
  dataPool:
    failureDomain: host
    erasureCoded:
      dataChunks: 2
      codingChunks: 1
  preservePoolsOnDelete: true
  gateway:
    port: 80
    instances: 2
