# Source: rook-ceph
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: replicapool
  namespace: rook-ceph
  annotations:
    noa.re/deploy-id: adf6c6605b51894b
spec:
  failureDomain: host
  replicated:
    size: 3
