# Source: csi-drivers
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: replicapool
  namespace: rook-ceph
  annotations:
    noa.re/manifest-id: 594b468e6d011bf1
spec:
  failureDomain: host
  replicated:
    size: 3
