# Source: rook
kind: ConfigMap
apiVersion: v1
metadata:
  name: rook-ceph-operator-config
  namespace: rook-ceph
  labels:
    operator: rook
    storage-backend: ceph
    app.kubernetes.io/name: rook-ceph
    app.kubernetes.io/instance: rook
    app.kubernetes.io/version: v1.20.7
    app.kubernetes.io/part-of: rook-ceph-operator
    app.kubernetes.io/created-by: helm
  annotations:
    noa.re/deploy-id: ea4539c613483289
data:
  ROOK_LOG_LEVEL: INFO
  ROOK_CEPH_COMMANDS_TIMEOUT_SECONDS: '15'
  ROOK_OBC_WATCH_OPERATOR_NAMESPACE: 'true'
  ROOK_OBC_ALLOW_ADDITIONAL_CONFIG_FIELDS: maxObjects,maxSize
  ROOK_CEPH_ALLOW_LOOP_DEVICES: 'false'
  ROOK_CEPH_MON_RUN_AS_ROOT: 'false'
  ROOK_DELETE_UNUSED_CRUSH_RULES: 'true'
  ROOK_ENABLE_DISCOVERY_DAEMON: 'true'
