# Source: csi-drivers
apiVersion: csi.ceph.io/v1
kind: Driver
metadata:
  name: rook-ceph.rbd.csi.ceph.com
  namespace: rook-ceph
  annotations:
    noa.re/deploy-id: ea4539c613483289
spec:
  log:
    verbosity: 0
    rotation:
      maxFiles: 7
      maxLogSize: 10G
      periodicity: daily
  enableFencing: false
  grpcTimeout: 30
  snapshotPolicy: none
  generateOMapInfo: false
  fsGroupPolicy: File
  attachRequired: true
  deployCsiAddons: false
  cephFsClientType: kernel
  kernelMountOptions: {}
  fuseMountOptions: {}
  nodePlugin:
    serviceAccountName: rook-ceph-rbd-csi-ceph-com-nodeplugin-sa
    tolerations: []
    imagePullPolicy: IfNotPresent
    volumes: []
  controllerPlugin:
    serviceAccountName: rook-ceph-rbd-csi-ceph-com-ctrlplugin-sa
    hostNetwork: false
    replicas: 1
    privileged: false
    tolerations: []
    volumes: []
