# Source: csi-drivers
apiVersion: csi.ceph.io/v1
kind: OperatorConfig
metadata:
  name: ceph-csi-operator-config
  namespace: rook-ceph
  annotations:
    noa.re/deploy-id: e35d63c21070af1d
spec:
  driverSpecDefaults:
    log:
      verbosity: 0
      rotation:
        maxFiles: 7
        maxLogSize: 10G
        periodicity: daily
    imageSet:
      name: rook-csi-operator-image-set-configmap
    enableFencing: false
    grpcTimeout: 30
    snapshotPolicy: none
    generateOMapInfo: false
    fsGroupPolicy: File
    attachRequired: true
    deployCsiAddons: false
    cephFsClientType: kernel
    kernelMountOptions: {}
    fuseMountOptions: {}
    nodePlugin:
      kubeletDirPath: /var/lib/kubelet
      priorityClassName: system-node-critical
      tolerations: []
      imagePullPolicy: IfNotPresent
      volumes: []
    controllerPlugin:
      hostNetwork: false
      replicas: 1
      privileged: false
      priorityClassName: system-cluster-critical
      tolerations: []
      volumes: []
      imagePullPolicy: IfNotPresent
