# Source: rook
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ceph-csi-leader-election-role
  namespace: rook-ceph
  labels:
    app.kubernetes.io/name: ceph-csi
    app.kubernetes.io/instance: rook
    app.kubernetes.io/version: v1.0.4
  annotations:
    noa.re/deploy-id: ea4539c613483289
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - patch
