# Source: csi-drivers
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rook-ceph-rbd-csi-ceph-com-nodeplugin-rb
  namespace: rook-ceph
  annotations:
    noa.re/deploy-id: ea4539c613483289
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rook-ceph-rbd-csi-ceph-com-nodeplugin-r
subjects:
- kind: ServiceAccount
  name: rook-ceph-rbd-csi-ceph-com-nodeplugin-sa
  namespace: rook-ceph
