# Source: rook
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rook-ceph-default
  namespace: rook-ceph
  labels:
    operator: rook
    storage-backend: ceph
    app.kubernetes.io/name: rook-ceph
    app.kubernetes.io/instance: rook
    app.kubernetes.io/version: v1.20.7
    app.kubernetes.io/part-of: rook-ceph-operator
    app.kubernetes.io/created-by: helm
  annotations:
    noa.re/deploy-id: ea4539c613483289
