# Source: rook
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ceph-csi
  labels:
    app.kubernetes.io/name: ceph-csi
    app.kubernetes.io/instance: rook
    app.kubernetes.io/version: v1.0.4
  namespace: rook-ceph
  annotations:
    noa.re/deploy-id: ea4539c613483289
automountServiceAccountToken: true
