# Source: surrealdb
apiVersion: v1
kind: Service
metadata:
  name: surrealdb
  labels:
    app.kubernetes.io/name: surrealdb
    app.kubernetes.io/instance: surrealdb
    app.kubernetes.io/version: 2.6.5
  namespace: surrealdb
  annotations:
    noa.re/manifest-id: 8162b1f81143bbc0
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: surrealdb
    app.kubernetes.io/instance: surrealdb
