# Source: surrealdb
apiVersion: v1
kind: ServiceAccount
metadata:
  name: surrealdb
  labels:
    app.kubernetes.io/name: surrealdb
    app.kubernetes.io/instance: surrealdb
    app.kubernetes.io/version: 2.6.5
  namespace: surrealdb
  annotations:
    noa.re/manifest-id: a5fff0d09f919cfb
