# Source: kubelet-csr-approver
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubelet-csr-approver
  namespace: kubelet-csr-approver
  labels:
    app.kubernetes.io/name: kubelet-csr-approver
    app.kubernetes.io/instance: kubelet-csr-approver
    app.kubernetes.io/version: v1.2.15
  annotations:
    noa.re/deploy-id: ebca94d31b0b2503
