# Source: k8s.noa.re
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-noa-re-config
  namespace: jwksproxy
  annotations:
    noa.re/deploy-id: 8912c10454c4e72c
data:
  jwksproxy.toml: |-
    origin = "k8s.noa.re"
    emit_x5c = true
