# Source: relcoord.noa.re
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: relcoord-noa-re
  namespace: relcoord
  annotations:
    noa.re/manifest-id: f4e9fda47a35fde2
spec:
  dnsNames:
  - relcoord.noa.re
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Always
  secretName: relcoord-noa-re-tls
