# Source: idcat.noa.re
apiVersion: noa.re/v1alpha1
kind: RandomSecret
metadata:
  name: idcat-noa-re
  namespace: idcat
  annotations:
    noa.re/manifest-id: a2e96736aa620ee5
spec:
  secrets:
  - name: webhook
