# Source: idcat.noa.re
apiVersion: noa.re/v1alpha1
kind: RandomSecret
metadata:
  name: idcat-noa-re
  namespace: idcat
  annotations:
    noa.re/manifest-id: 14b96fe5bcea67ba
spec:
  secrets:
  - name: token
