# Source: idcat.noa.re
apiVersion: v1
kind: Service
metadata:
  name: idcat-noa-re
  namespace: idcat
  annotations:
    noa.re/deploy-id: e18827f79ff691f0
spec:
  selector:
    app: idcat-noa-re
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
