# Source: mimir
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mimir-ingester
  labels:
    app.kubernetes.io/name: mimir
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/component: ingester
    app.kubernetes.io/version: 3.2.0
  namespace: mimir
  annotations:
    noa.re/manifest-id: f04689459bc538b4
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mimir
      app.kubernetes.io/instance: mimir
      app.kubernetes.io/component: ingester
  maxUnavailable: 1
