# Source: mimir
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mimir-rollout-operator-webhook-role
  namespace: mimir
  annotations:
    noa.re/manifest-id: c95ab6d785451ae4
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - update
  - get
  resourceNames:
  - certificate
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - create
