# Source: mimir
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mimir-rollout-operator
  namespace: mimir
  labels:
    app.kubernetes.io/name: rollout-operator
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/version: v0.38.1
  annotations:
    noa.re/manifest-id: 93c68060d07e8134
