# Source: mimir
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mimir
  labels:
    app.kubernetes.io/name: mimir
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/version: 3.2.0
  namespace: mimir
  annotations:
    noa.re/manifest-id: a54aceb27917761a
