# Source: mimir
apiVersion: v1
kind: Service
metadata:
  name: mimir-store-gateway-zone-c
  labels:
    app.kubernetes.io/name: mimir
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/component: store-gateway
    app.kubernetes.io/part-of: memberlist
    app.kubernetes.io/version: 3.2.0
    name: store-gateway-zone-c
    rollout-group: store-gateway
    zone: zone-c
  namespace: mimir
  annotations:
    noa.re/manifest-id: 1940131fb98d417e
spec:
  type: ClusterIP
  internalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    name: http-metrics
    targetPort: http-metrics
  - port: 9095
    protocol: TCP
    name: grpc
    targetPort: grpc
  selector:
    app.kubernetes.io/name: mimir
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/component: store-gateway
    rollout-group: store-gateway
    zone: zone-c
