# Source: mimir
apiVersion: v1
kind: Service
metadata:
  name: mimir-alertmanager-headless
  labels:
    app.kubernetes.io/name: mimir
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/component: alertmanager
    app.kubernetes.io/part-of: memberlist
    app.kubernetes.io/version: 3.2.0
    prometheus.io/service-monitor: 'false'
  namespace: mimir
  annotations:
    noa.re/manifest-id: cdf308525815f8ea
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - port: 8080
    protocol: TCP
    name: http-metrics
    targetPort: http-metrics
  - port: 9095
    protocol: TCP
    name: grpc
    targetPort: grpc
  - port: 9094
    protocol: TCP
    name: cluster
  selector:
    app.kubernetes.io/name: mimir
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/component: alertmanager
