# Source: randomsecret
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: randomsecret
  labels:
    app.kubernetes.io/name: randomsecret
    app.kubernetes.io/instance: randomsecret
    app.kubernetes.io/version: 0.1.4
  annotations:
    noa.re/deploy-id: 5d0b9439ed204139
rules:
- apiGroups:
  - noa.re
  resources:
  - randomsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - noa.re
  resources:
  - randomsecrets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - patch
