# Source: teleport-kube-agent
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: teleport-kube-agent
  annotations:
    noa.re/deploy-id: c98c3d6c66e5a0f3
rules:
- apiGroups:
  - ''
  resources:
  - users
  - groups
  - serviceaccounts
  verbs:
  - impersonate
- apiGroups:
  - ''
  resources:
  - services
  verbs:
  - list
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - authorization.k8s.io
  resources:
  - selfsubjectaccessreviews
  verbs:
  - create
