# Source: rook
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rook-ceph-mgr-system
  labels:
    operator: rook
    storage-backend: ceph
    app.kubernetes.io/name: rook-ceph
    app.kubernetes.io/instance: rook
    app.kubernetes.io/version: v1.20.7
    app.kubernetes.io/part-of: rook-ceph-operator
    app.kubernetes.io/created-by: helm
  annotations:
    noa.re/deploy-id: ea4539c613483289
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
