# Source: nack
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nats-aws-auth
  annotations:
    noa.re/manifest-id: 15e3c013a2981606
rules:
- apiGroups:
  - ''
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
