# Source: loki
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
    app.kubernetes.io/version: 3.7.8
  name: loki-clusterrole
  annotations:
    noa.re/manifest-id: 6b6ce9bf3717d5c0
rules: []
