# Source: rook
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ceph-csi-clientprofilemapping-editor-role
  labels:
    app.kubernetes.io/name: ceph-csi
    app.kubernetes.io/instance: rook
    app.kubernetes.io/version: v1.0.4
  annotations:
    noa.re/deploy-id: ea4539c613483289
rules:
- apiGroups:
  - csi.ceph.io
  resources:
  - clientprofilemappings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - csi.ceph.io
  resources:
  - clientprofilemappings/status
  verbs:
  - get
