# Source: randomsecret
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: randomsecret
  labels:
    app.kubernetes.io/name: randomsecret
    app.kubernetes.io/instance: randomsecret
    app.kubernetes.io/version: 0.1.4
  annotations:
    noa.re/deploy-id: 5d0b9439ed204139
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: randomsecret
subjects:
- kind: ServiceAccount
  name: randomsecret
  namespace: randomsecret
