# Source: mimir
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: prepare-downscale-mimir
  labels:
    grafana.com/inject-rollout-operator-ca: 'true'
    grafana.com/namespace: mimir
    app.kubernetes.io/name: rollout-operator
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/version: v0.38.1
  annotations:
    noa.re/manifest-id: b8f4dc428fdb9c83
webhooks:
- name: prepare-downscale-mimir.grafana.com
  clientConfig:
    service:
      namespace: mimir
      name: mimir-rollout-operator
      path: /admission/prepare-downscale
      port: 443
  rules:
  - operations:
    - UPDATE
    apiGroups:
    - apps
    apiVersions:
    - v1
    resources:
    - statefulsets
    - statefulsets/scale
    scope: Namespaced
  admissionReviewVersions:
  - v1
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: mimir
  sideEffects: NoneOnDryRun
  matchPolicy: Equivalent
  timeoutSeconds: 10
  failurePolicy: Fail
