# Source: cilium
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cilium-tlsinterception-secrets
  namespace: cilium-secrets
  labels:
    app.kubernetes.io/part-of: cilium
  annotations:
    noa.re/deploy-id: 2ca554aa1f007f58
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
