# Source: cilium
apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: nadia-ipv6
  namespace: kube-system
  annotations:
    noa.re/deploy-id: eac27d93fc83db32
spec:
  authSecretRef: nadia-bgp-auth
  families:
  - afi: ipv6
    safi: unicast
    advertisements:
      matchLabels:
        advertise: fruktsallad-pod-cidrs
