# Source: cilium
apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: nadia-ipv4
  namespace: kube-system
  annotations:
    noa.re/manifest-id: a420095616ccf6dc
spec:
  authSecretRef: nadia-bgp-auth
  families:
  - afi: ipv4
    safi: unicast
    advertisements:
      matchLabels:
        advertise: fruktsallad-pod-cidrs
