# Source: cilium
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cilium-bgp-control-plane-secrets
  namespace: kube-system
  labels:
    app.kubernetes.io/part-of: cilium
  annotations:
    noa.re/manifest-id: d600cc1e88ebd737
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
