# Source: idmouse
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idmouse
  labels:
    app: idmouse
  namespace: idmouse
  annotations:
    noa.re/deploy-id: 671eaddcdde7d3d1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: idmouse
  template:
    metadata:
      labels:
        app: idmouse
      annotations:
        checksum/config: 33b73759d411154182638d199151f85f36715c8692ceefb0c039b3abd3f11999
    spec:
      serviceAccountName: idmouse
      containers:
      - name: idmouse
        image: nresare/idmouse
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: idmouse-config
          mountPath: /config
      volumes:
      - name: idmouse-config
        configMap:
          name: idmouse-config
