# Source: idmouse
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idmouse
  labels:
    app: idmouse
  namespace: idmouse
  annotations:
    noa.re/deploy-id: 26f0c2d70e87ffe9
spec:
  replicas: 2
  selector:
    matchLabels:
      app: idmouse
  template:
    metadata:
      labels:
        app: idmouse
      annotations:
        checksum/config: 659468023f4f17350a4163a933a33e53a7991192b276b42923b96ddcc3dbbcec
    spec:
      serviceAccountName: idmouse
      containers:
      - name: idmouse
        image: nresare/idmouse
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: idmouse-config
          mountPath: /config
      volumes:
      - name: idmouse-config
        configMap:
          name: idmouse-config
