# Source: idmouse
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: idmouse-signing-keys
  namespace: idmouse
  annotations:
    noa.re/deploy-id: f5b39b5ee9a8bcd5
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  resourceNames:
  - idmouse-signing-keys
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
