# Source: idmouse
apiVersion: v1
kind: Service
metadata:
  name: idmouse
  namespace: idmouse
  annotations:
    noa.re/manifest-id: fd727839ec8c6d3f
spec:
  type: ClusterIP
  selector:
    app: idmouse
  ports:
  - name: http
    port: 80
    targetPort: http
