# Source: id.noa.re
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: id-noa-re
  namespace: idelephant
  annotations:
    noa.re/manifest-id: 42244ee29bb6c6a8
spec:
  dnsNames:
  - id.noa.re
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Always
  secretName: id-noa-re-tls
