# Source: id.noa.re
apiVersion: apps/v1
kind: Deployment
metadata:
  name: id-noa-re
  labels:
    app: id-noa-re
  namespace: idelephant
  annotations:
    noa.re/manifest-id: 938280f9ab14bae6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: id-noa-re
  template:
    metadata:
      labels:
        app: id-noa-re
      annotations:
        checksum/config: bfa2dc85ae0e1ba687f4ca8b431dfffc84510d6cbcd07402533a8a5fd82b06a4
    spec:
      containers:
      - name: id-noa-re
        image: repo.noa.re/idelephant:0.2.3-80bc6519
        args:
        - -c
        - /config/idelephant.toml
        ports:
        - name: https
          containerPort: 8443
          protocol: TCP
        volumeMounts:
        - name: tls
          mountPath: /tls
          readOnly: true
        - name: id-noa-re-config
          mountPath: /config
        - name: email-password
          mountPath: /email-password
        - name: tokens
          mountPath: /var/run/secrets/tokens
          readOnly: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: https
            scheme: HTTPS
      volumes:
      - name: tls
        secret:
          secretName: id-noa-re-internal-tls
      - name: id-noa-re-config
        configMap:
          name: id-noa-re-config
      - name: email-password
        secret:
          secretName: email-password
      - name: tokens
        projected:
          sources:
          - serviceAccountToken:
              path: idmouse
              expirationSeconds: 3600
              audience: idmouse
