# Source: webhook-poker
apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-poker-config
  namespace: webhook-poker
  annotations:
    noa.re/manifest-id: 1911c1ec00e46977
data:
  webhook-poker.toml: |
    listen = "0.0.0.0"
    port = 8080
    log-level = "INFO"

    [nats]
    servers = ["nats://nats.nats.svc"]
    name = "webhook-poker"  # client name shown in NATS server connection listings
    token-path = "/var/run/secrets/tokens/nats"

    [[target]]
    name = "argo"
    url = "http://argocd-server.argo.svc/api/webhook"

    [[subscription]]
    name = "argo-poker"
    stream = "github-events"
    targets = ["argo"]
    headers = { X-GitHub-Event = "push" }
