# Source: argocd
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-gpg-keys-cm
  namespace: argo
  labels:
    app.kubernetes.io/name: argocd-gpg-keys-cm
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v3.5.2
  annotations:
    noa.re/deploy-id: 7e7ae041eb0e1fd6
