# Source: argocd
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argo
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v3.5.4
  annotations:
    noa.re/manifest-id: 62ad782a8377009a
data:
  policy.csv: ''
  policy.default: ''
  policy.matchMode: glob
  scopes: '[groups]'
