# Source: randomsecret
apiVersion: apps/v1
kind: Deployment
metadata:
  name: randomsecret
  namespace: randomsecret
  labels:
    app.kubernetes.io/name: randomsecret
    app.kubernetes.io/instance: randomsecret
    app.kubernetes.io/version: 0.1.4
  annotations:
    noa.re/deploy-id: 5d0b9439ed204139
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: randomsecret
      app.kubernetes.io/instance: randomsecret
  template:
    metadata:
      labels:
        app.kubernetes.io/name: randomsecret
        app.kubernetes.io/instance: randomsecret
    spec:
      serviceAccountName: randomsecret
      securityContext:
        runAsNonRoot: true
      containers:
      - name: randomsecret
        image: public.ecr.aws/portswigger-platform/randomsecret:0.1.4
        imagePullPolicy: IfNotPresent
        env:
        - name: RUST_LOG
          value: info
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
