# Source: randomsecret
apiVersion: v1
kind: ServiceAccount
metadata:
  name: randomsecret
  namespace: randomsecret
  labels:
    app.kubernetes.io/name: randomsecret
    app.kubernetes.io/instance: randomsecret
    app.kubernetes.io/version: 0.1.4
  annotations:
    noa.re/deploy-id: 5d0b9439ed204139
