# Source: teleport-cluster
apiVersion: v1
kind: ServiceAccount
metadata:
  name: teleport-cluster
  namespace: teleport-cluster
  labels:
    app.kubernetes.io/name: teleport-cluster
    app.kubernetes.io/instance: teleport-cluster
    app.kubernetes.io/component: auth
    app.kubernetes.io/version: 18.11.2
    teleport.dev/majorVersion: '18'
  annotations:
    noa.re/manifest-id: a3ee92b65be8ade2
automountServiceAccountToken: false
