# Source: acme-dns
apiVersion: apps/v1
kind: Deployment
metadata:
  name: acme-dns
  labels:
    app: acme-dns
  namespace: acme-dns
  annotations:
    noa.re/deploy-id: 909655b7e03c03f3
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: acme-dns
  template:
    metadata:
      labels:
        app: acme-dns
      annotations:
        checksum/config: 8112411ac7ad004b2ac314c519b6b129cef05bb2fcc2536fdd719e00d035df79
    spec:
      volumes:
      - name: db
        persistentVolumeClaim:
          claimName: acme-dns
      - name: acme-dns-etc-acme-dns
        configMap:
          name: acme-dns-etc-acme-dns
      securityContext:
        fsGroup: 65532
      containers:
      - name: acme-dns
        securityContext:
          allowPrivilegeEscalation: false
          fsGroup: 65532
          fsUser: 65532
        image: nresare/acme-dns:v1.1-distroless
        volumeMounts:
        - mountPath: /db
          name: db
        - name: acme-dns-etc-acme-dns
          mountPath: /etc/acme-dns
        ports:
        - name: web
          containerPort: 1080
          protocol: TCP
        - name: dns-tcp
          containerPort: 1053
          protocol: TCP
        - name: dns
          containerPort: 1053
          protocol: UDP
