# Source: acme-dns
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: acme-dns
  namespace: acme-dns
  annotations:
    noa.re/manifest-id: bd3412a586f154da
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
