# Source: tempo
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tempo
  namespace: tempo
  labels:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/version: 3.1.0
  annotations:
    noa.re/manifest-id: a1e644f867f541ed
automountServiceAccountToken: true
