# Source: teleport-kube-agent
apiVersion: v1
kind: Secret
metadata:
  name: teleport-kube-agent-join-token
  namespace: teleport
  annotations:
    noa.re/deploy-id: c98c3d6c66e5a0f3
type: Opaque
stringData:
  auth-token: |
    kubernetes-token
