# Source: cert-manager
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-local-selfsigned
  namespace: cert-manager
  annotations:
    noa.re/manifest-id: 3af60a71cb9cd01f
spec:
  selfSigned: {}
