# Source: cert-manager
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-local
  namespace: cert-manager
  annotations:
    noa.re/manifest-id: 50e71b5d5db1c591
spec:
  ca:
    secretName: cluster-local-ca
