# Source: trust-manager
apiVersion: v1
kind: Service
metadata:
  name: trust-manager-metrics
  namespace: cert-manager
  labels:
    app: trust-manager
    app.kubernetes.io/component: metrics
    app.kubernetes.io/name: trust-manager
    app.kubernetes.io/instance: trust-manager
    app.kubernetes.io/version: v0.25.0
  annotations:
    noa.re/deploy-id: 964b51b71783fe70
spec:
  type: ClusterIP
  ports:
  - port: 9402
    targetPort: 9402
    protocol: TCP
    name: metrics
  selector:
    app: trust-manager
