# Source: trust-manager
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: trust-manager
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: trust-manager
    app.kubernetes.io/instance: trust-manager
    app.kubernetes.io/version: v0.25.0
  annotations:
    noa.re/deploy-id: 964b51b71783fe70
