# Source: envoy-gateway
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unifi-noa-re
  namespace: envoy-gateway-system
  annotations:
    noa.re/manifest-id: ca6d397bd44a41a7
spec:
  dnsNames:
  - unifi.noa.re
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Always
  secretName: unifi-noa-re-tls
