# Source: envoy-gateway
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: envoy-gateway-gateway-helm-infra-manager
  namespace: envoy-gateway-system
  labels:
    app.kubernetes.io/name: gateway-helm
    app.kubernetes.io/instance: envoy-gateway
    app.kubernetes.io/version: v1.9.1
  annotations:
    noa.re/deploy-id: adb18aacd20879bd
rules:
- apiGroups:
  - ''
  resources:
  - serviceaccounts
  - services
  - configmaps
  verbs:
  - create
  - get
  - list
  - delete
  - deletecollection
  - patch
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  verbs:
  - create
  - get
  - list
  - delete
  - deletecollection
  - patch
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - get
  - list
  - delete
  - deletecollection
  - patch
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - get
  - list
  - delete
  - deletecollection
  - patch
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - clustertrustbundles
  verbs:
  - list
  - get
  - watch
