# Source: noa.re
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: noa-re
  namespace: web
  annotations:
    noa.re/deploy-id: b720b21606ad7431
spec:
  targetRefs:
  - group: ''
    kind: Service
    name: noa-re
    sectionName: https
  validation:
    caCertificateRefs:
    - group: ''
      kind: ConfigMap
      name: cluster-local-ca
    hostname: noa-re.web.svc
