# Source: zq.lu
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zq-lu-internal
  namespace: web
  annotations:
    noa.re/manifest-id: 6f498397fbda3276
spec:
  dnsNames:
  - zq-lu.web.svc
  duration: 2160h
  issuerRef:
    name: cluster-local
    kind: ClusterIssuer
    group: cert-manager.io
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  renewBefore: 360h
  secretName: zq-lu-internal-tls
  usages:
  - digital signature
  - server auth
