# Source: noa.re
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: noa-re-internal
  namespace: web
  annotations:
    noa.re/manifest-id: 5482c3253bf6d738
spec:
  dnsNames:
  - noa-re.web.svc
  duration: 2160h
  issuerRef:
    name: cluster-local
    kind: ClusterIssuer
    group: cert-manager.io
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  renewBefore: 360h
  secretName: noa-re-internal-tls
  usages:
  - digital signature
  - server auth
