# Source: zq.lu
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: zq-lu
  namespace: web
  annotations:
    noa.re/manifest-id: 2b7298c0dd5b4bc6
spec:
  gatewayClassName: eg
  listeners:
  - name: zq-lu
    protocol: HTTPS
    hostname: zq.lu
    port: 443
    tls:
      certificateRefs:
      - name: zq-lu-tls
        group: ''
        kind: Secret
